title: "Collections Digitization Glossary"
documentation-landing-page:
github-repo: https://github.com/ben-norton/specimen-digitization-glossary
source-data-files:
source-md-files:
last-modified: 20251006
comments: